edoweb/to.science.drupal

- edoweb/edoweb.js
- edoweb/edoweb.module
- edoweb/edoweb_edit.js
- edoweb/edoweb_tree.js
> Retain only facets upon navigation

- edoweb/edoweb.install
- edoweb/edoweb.module
- edoweb/edoweb_edit.js
- edoweb_field/edoweb_field.module
Please run update script
Known problem: the catalogLink can currently not be rendered as a
link due to a bug in the rdfQuery JS library
> Add fields for subjectChain, collectedBy and catalogLink

- edoweb/edoweb.install
- edoweb/edoweb.module
> Remove field_edoweb_webpage_archived and field_edoweb_catalog_link

- edoweb_storage/EdowebAPIClient.inc
> Fix API parameter for index action

- edoweb/edoweb_edit.js
> Fix automatically adding ling to parallel editon when importing

- edoweb/edoweb.module
- edoweb/edoweb_view.js
> Remove live search behavior

- edoweb/edoweb.js
- edoweb/edoweb_edit.js
- edoweb/edoweb_view.js
> Implement removal of form fields

- edoweb/edoweb.module
- edoweb/edoweb_edit.js
- edoweb_storage/EdowebAPIClient.inc
- edoweb_storage/edoweb_storage.module
Custom names for metadata templates
> Edozwo 415

- edoweb/LinkedDataClient.inc
- edoweb/edoweb.module
- edoweb/edoweb_edit.js
- edoweb_storage/EdowebAPIClient.inc
> Implement setting access rights for subtree

- edoweb/edoweb.install
- edoweb/edoweb.module
- german.po
Please run update script as the title is set on instance creation. No need to re-upload translation file.
> Fix title of field_edoweb_title_other

- edoweb/edoweb.install
- edoweb/edoweb.js
- edoweb/edoweb.module
- edoweb/edoweb_edit.js
- edoweb/edoweb_view.js
- edoweb_field/edoweb_field.module
- edoweb_storage/EdowebAPIClient.inc
- edoweb_storage/edoweb_storage.module
First take, deployed to http://edoweb.literarymachine.net/
TODO: configure fields to be displayed in compact view mode
> EDOZWO-459

- edoweb/edoweb.js
- edoweb/edoweb.module
> Fix links to point at local representations

- edoweb/edoweb.js
- edoweb/edoweb.module
- edoweb/edoweb_edit.js
- edoweb/jquery.blockUI.js
> Block UI for corresponding actions

- edoweb/edoweb.install
- edoweb/edoweb.module
- edoweb_storage/edoweb_storage.module
- Set the corresponding API user and password in edoweb/config/storage
- Please run update script
TODO: decide which role has precedence if a user has multiple roles
> Add subscriber and remote roles and permissions

- edoweb/edoweb.js
- edoweb/edoweb.module
- edoweb/edoweb_view.js
- edoweb_storage/EdowebAPIClient.inc
> Add column last modified label, resolved by AJAX

- edoweb/edoweb_edit.js
- edoweb_storage/edoweb_storage.module
- Action is triggered via link next to title field
- Currently only available for file resources
> Implement adopting title from parent

- edoweb/EdowebBasicEntity.inc
- edoweb/edoweb.module
- edoweb_storage/edoweb_storage.module
> Show PDF tumbnails in default view for files

- edoweb/edoweb.js
> Sort by updated column if present

- edoweb_storage/EdowebAPIClient.inc
> Add contentType parameter to API call

- edoweb/edoweb.module
- edoweb/edoweb_tree.js
> Disable expansion of empty sub trees

- edoweb/edoweb_edit.js
> Open overlay-links in new window

- edoweb/edoweb_edit.js
> Fix position and caption of import button

- edoweb/edoweb.js
> Fix sorting alphabetically by week days

- edoweb/edoweb.module
> Resolve user IDs in factes

- edoweb/edoweb.module
- edoweb_storage/EdowebAPIClient.inc
Fixes EDOZWO-503, please clear cache.
> Add status tab

- edoweb/LinkedDataClient.inc
- edoweb_storage/EdowebAPIClient.inc
> Fix missing HTTP 404

- edoweb/edoweb.install
- edoweb/edoweb.module
Please run update script. We have to test if this actually fixes EDOZWO-494 (which we believe to be a browser issue).
> Update metadata type of field_edoweb_datastream

- edoweb_field/edoweb_field.module
> Fix missing label facets

- edoweb/LinkedDataClient.inc
- edoweb/edoweb.module
- edoweb/edoweb_edit.js
- edoweb/edoweb_tree.js
- edoweb_storage/EdowebAPIClient.inc
- edoweb_storage/edoweb_storage.module
> Tree navigator

- edoweb/edoweb.install
- edoweb/edoweb.module
- edoweb/edoweb_edit.js
- edoweb_storage/EdowebAPIClient.inc
Please keep PR open, optional type filtering still to come.
> EDOZWO-520

- edoweb/edoweb.module
- edoweb_storage/edoweb_storage.module
- probably the first of a series of similar commits
- @literarymachine: idea is to get rid of the term "edoweb"
in names, pathes, etc.
> remove the word edoweb

- edoweb/edoweb.install
- edoweb/edoweb.module
> Update field_edoweb_doi mapping

- edoweb/edoweb_tree.js
> Add js reload after appending to the tree

- edoweb/LinkedDataClient.inc
Fixes EDOZWO-529, e.g. http://edoweb.literarymachine.net/resource/edoweb:5949007
> Fix following sameAs links

- edoweb/edoweb.module
- edoweb_field/edoweb_field.module
> Fix missing download links in tree navigator

- edoweb/edoweb.js
- edoweb/edoweb.module
> Fix sorting table rows by update time

- edoweb/edoweb.module
- edoweb_storage/EdowebAPIClient.inc
- edoweb_storage/edoweb_storage.module
> Set UserId header, add lastModifiedBy facet

- edoweb_field/edoweb_field.module
> Get rid of strict warning

- edoweb/edoweb.module
> Flush output buffer before sending file

- edoweb/edoweb.js
- edoweb_field/edoweb_field.module
> Fix missing entries in table view

- edoweb/edoweb.js
- edoweb/edoweb.module
- edoweb/edoweb_tree.js
- german.po
Please reload german.po at admin/config/regional/translate/import and clear cache.
> Update UI translations

- edoweb/edoweb.module
- edoweb_storage/EdowebAPIClient.inc
> EDOZWO-531

- edoweb/edoweb.module
> Optionally include non top-level objects in search

- edoweb/EdowebBasicEntity.inc
- edoweb/edoweb.module
- edoweb_storage/EdowebAPIClient.inc
- edoweb_storage/edoweb_storage.module
Contributors and creators are added when viewing an entity in 'compact' mode, e.g. in a result listing.
> Add contributor and creator to compact title

- edoweb/edoweb.js
- edoweb/edoweb.module
> Show error messages and pages on AJAX navigation

- edoweb/edoweb.module
> Display status messages instead of numeric codes

- edoweb/edoweb.install
- edoweb/edoweb.module
- edoweb_storage/edoweb_storage.module
Fixes FRL-49, please run update script.
> Add field for thesis information

- edoweb_storage/EdowebAPIClient.inc
Facet size set to 99 as elasticsearch currently does not have an option to simply include all terms.
Fixes FRL-43
> Increase facet size for lastModifiedBy and createdBy

- edoweb/EdowebBasicEntity.inc
- edoweb/edoweb.install
- edoweb/edoweb.module
- edoweb_storage/EdowebAPIClient.inc
- edoweb_storage/edoweb_storage.module
Select roles at admin/people/permissions for "Administer Edoweb Repository"
Fixes FRL-52
> Add repository configuration

- edoweb/edoweb.module
Please clear cache
Fixes FRL-57
> Remove dates of birth and death for anonymous user

- edoweb/edoweb.module
> Add mets to transformer list

- edoweb_field/edoweb_field.module
- edoweb_storage/edoweb_storage.module
> Use etikett to look up entity labels

- edoweb/edoweb.module
- edoweb/edoweb_view.js
- edoweb_storage/EdowebAPIClient.inc
- german.po
Please reset cache & leave PR open
> Add pages to browse facets

- edoweb/edoweb.install
- edoweb/edoweb.module
Fixes FRL-79, please run update script.
> Fix weight of contributor and creator

- edoweb/edoweb.module
- edoweb_storage/EdowebAPIClient.inc
> Add configurable URN snid

- edoweb_field/edoweb_field.module
> Link to facets from field values

- edoweb/edoweb.install
- edoweb/edoweb.module
@jschnasse the data ends up in /metadata but not in .rdf, did I miss something?
https://api.edoweb-test.hbz-nrw.de/resource/edoweb:5949210/metadata
https://api.edoweb-test.hbz-nrw.de/resource/edoweb:5949210.rdf
Please run update script.
> Add regal:isPartOf field

- edoweb_field/edoweb_field.module
This reverts commit bfcce46f76f2eb24256ec4ea52637c7b1e700491.
> Revert "Link to facets from field values"

- edoweb/edoweb.module
> Show document count in facet only for current user

- edoweb/edoweb.module
> Show modified data only for users with edit perm

- edoweb/edoweb.install
- edoweb/edoweb.js
- edoweb/edoweb.module
- edoweb_field/edoweb_field.module
Fixes EDOZWO-567, please run update script.
Also, please re-enable the facets for type and medium at edoweb/config/settings
> Set type, medium and description as LD fields

- edoweb/edoweb.module
> Add link to facet pages

- edoweb/edoweb.module
> Fix ignored table column configuration

- edoweb/edoweb.install
- edoweb/edoweb.module
Fixes FRL-124, please run update script.
> Add HT-Number to bundles

- edoweb/edoweb.module
- edoweb_field/edoweb_field.module
- german.po
@literarymachine I wasn't able to apply translation. Ui still shows "Redakteur" and "[Bearb.]". What am I doing wrong?
> Add labels

- edoweb/EdowebBasicEntity.inc
- edoweb/edoweb.module
- edoweb_field/edoweb_field.module
- edoweb_storage/edoweb_storage.module
- german.po
You can configure the sub title ("compact view") fields at edoweb/config/settings, you probably want to disable `title` there because otherwise it is duplicated in the subtitle.
> Add author list as subtitle

- edoweb/LinkedDataClient.inc
- edoweb_storage/EdowebAPIClient.inc
- edoweb_storage/edoweb_storage.module
> Fix unicode encodings in literal values

- edoweb/edoweb.module
moving of submit button is required to get textarea and button in the same line
> Improve query field

- edoweb/edoweb.module
- edoweb_storage/EdowebAPIClient.inc
- edoweb_storage/edoweb_storage.module
> fix rdftype aka type facet

- edoweb_storage/edoweb_storage.module
- e.g. HTNummer
- remove special case for json fields of type text
> fix: sorting on text fields does not work

- edoweb/edoweb.module
this pull request must be applied together with pull request #97 of edoweb/regal-api
> add new option "once" in crawler settings interval

- edoweb/edoweb.module
dazu gehört Pull-Request #98 von regal-api
> add checkbox active in crawler settings

- edoweb/edoweb.install
- edoweb/edoweb.module
The patch solves the problem that part entities lose their parents. 
see Ticket for details
https://jira.hbz-nrw.de/browse/EDOZWO-628
> correct bracket setting within part entity in edoweb.info

- edoweb_field/warc.svg
replaces the memento clock icon with a new icon for warcs see also: https://jira.hbz-nrw.de/browse/EDOZWO-640
> replace memento svg with new warc icon

- edoweb/zettel.js
- send referrer to iframe
- if cancel is performed, get back referrer from iframe and
navigate to
> support cancel action

- edoweb/EdowebBasicEntity.inc
- http://php.net/manual/de/function.htmlentities.php
> encode single quotes

- edoweb/edoweb.module
needs regal-api EDOZWO-714 to work
frontend solution for gathering contents from multiple domains.
> Edozwo 714

- edoweb/edoweb.module
- add shortening for http adress of video uri
- label function only works that way
> display type video in table

- edoweb/edoweb.module
This reverts commit 8068beabaeee646ff9aa11a58b5a9d3b59c3875b.
> Revert "remove frontend functionalities for crawler selection"

- edoweb/edoweb.module
> EDOZWO-745: implements forms for additional wpull parameters

- edoweb/edoweb.module
format date if date is not formatted in dd-mm-yyyy
> catch parsing probs thrown from drupal localization

- edoweb/edoweb.module
implements election form for Browser ID
> Edozwo 745 browser

- edoweb/edoweb_edit.js
prevents Efoweb-Objects associated with catalogue-item from being skipped out of EL-Index via clicking Save Button
> Edozwo 764

- edoweb/edoweb.module
- edoweb_storage/EdowebAPIClient.inc
regal-drupal part of url moving history
> Edozwo 613

- edoweb/php/tree.php
- edoweb_storage/EdowebAPIClient.inc
- also, commit EDOZWO-1005: Hide all pdf icons in tree
> Use new ES index publicfulltext_<namespace>
